version: '3.8'

services:
  postgresql:
    container_name: project-04-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: project-04-db
      PGDATA: ./data/postgres
    volumes:
       - ./data/pg:/data/postgres
  cache:
    container_name: project-04-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data